# Generated by Django 4.2.18 on 2025-02-09 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_screenshot'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Screenshot',
            new_name='UploadedImage',
        ),
        migrations.RenameField(
            model_name='uploadedimage',
            old_name='timestamp',
            new_name='uploaded_at',
        ),
    ]
