services:
  backend:
    build: 
      context: .
      dockerfile: backend.Dockerfile
    networks:
      - commentarynet
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/mnt
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    entrypoint: tail -f /dev/null
    # entrypoint: daphne -b 0.0.0.0 -p 8000 realtime_commentary.asgi:application

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    networks:
      - commentarynet
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/mnt
    entrypoint: tail -f /dev/null
    # entrypoint: npm run start

  redis:
    image: redis:latest
    restart: always
    networks:
      - commentarynet
    ports:
      - "6379:6379"

networks:
  commentarynet:
    driver: bridge



